#!/bin/bash

TRAP=$1
FluidFSHost=$2

NASPoolTotalUsedMB=`snmpwalk -O Qv -v2c -c $TRAP $FluidFSHost nASPoolTotalUsedMB`
NASPoolTotalCapacityMB=`snmpwalk -O Qv -v2c -c $TRAP $FluidFSHost nASPoolTotalCapacityMB`
NASPoolTotalUnusedMB=`snmpwalk -O Qv -v2c -c $TRAP $FluidFSHost nASPoolTotalUnusedMB`

NASPoolTotalReservedMB=`snmpwalk -O Qv -v2c -c $TRAP $FluidFSHost nASPoolTotalReservedMB`
NASPoolTotalUnusedReservedMB=`snmpwalk -O Qv -v2c -c $TRAP $FluidFSHost nASPoolTotalUnusedReservedMB`
NASPoolTotalUnusedUnreservedMB=`snmpwalk -O Qv -v2c -c $TRAP $FluidFSHost nASPoolTotalUnusedUnreservedMB`


echo "NAS Pool free $(bc <<< "scale=3;${NASPoolTotalUnusedMB//\"}") MB"
echo "NAS Pool free $(bc <<< "scale=3;${NASPoolTotalUnusedMB//\"}/1024/1024") TB"
echo "NAS Pool Total $(bc <<< "scale=3;${NASPoolTotalCapacityMB//\"}") MB"
echo "NAS Pool Total $(bc <<< "scale=3;${NASPoolTotalCapacityMB//\"}/1024/1024") TB"
echo "Unreserved free $(bc <<< "scale=2;${NASPoolTotalUnusedUnreservedMB//\"}") MB"
echo "Unreserved free $(bc <<< "scale=2;${NASPoolTotalUnusedUnreservedMB//\"}/1024/1024") TB"



echo ""
echo "NAS Container space by use"
echo "Reserved free $(bc <<< "scale=2;${NASPoolTotalUnusedReservedMB//\"}") MB"
echo "Reserved free $(bc <<< "scale=2;${NASPoolTotalUnusedReservedMB//\"}/1024/1024") TB"
echo "Reserved TOTAL $(bc <<< "scale=2;${NASPoolTotalReservedMB//\"}") MB"
echo "Reserved TOTAL $(bc <<< "scale=2;${NASPoolTotalReservedMB//\"}/1024/1024") TB"
echo "Reserved Used $(bc <<< "scale=2;(${NASPoolTotalReservedMB//\"} - ${NASPoolTotalUnusedReservedMB//\"})") MB"
echo "Reserved Used $(bc <<< "scale=2;(${NASPoolTotalReservedMB//\"} - ${NASPoolTotalUnusedReservedMB//\"})/1024/1024") TB"
